"Id","ParentId","Type","CreatedById","CreatedDate","Body","Title","LinkUrl","RelatedRecordId","InsertedById","LastModifiedDate"
"0D5Qk00000VsrGzKAJ","500Qk00000LJtW9IAL","TextPost","0054u000006gpoFAAQ","2025-01-31T16:32:21.000Z","Description: Full error:

30/01/2025 19:00:31	ERROR	AZUREADINVENTORY	Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Tasks.AADInventoryScanTask.InternalProcessRecord	""System.InvalidOperationException: ExecuteScalar requires an open and available Connection. The connection's current state is closed.     at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)     at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)     at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)     at System.Data.SqlClient.SqlCommand.ExecuteScalar()     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.CalculateEffectiveGroupMembership(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.FinalizeScan(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.Finish(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Tasks.AADInventoryScanTask.InternalProcessRecord()""	NYCDOE.ONMICROSOFT.COM	DCExtract	11052	8124	15696

Prior to these runs we were getting a UNIQUE key constraint so we dropped the data and then resscaned.  There was a successful run and then 3 runs with this error.  Seems to always happen after here:
28/01/2025 19:00:49	INFO	AZUREADINVENTORY	Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Tasks.AADInventoryScanTask.InternalProcessRecord	""Begin effective group membership calculation""	NYCDOE.ONMICROSOFT.COM	DCExtract	14948	2756	11964

But it does look to be immediate not some time inbetween.  The timeout on the job is set to 1440 so def not that much time has passed.

I see another open case with the same issue: 00433160

Attaching logs for the past 4 runs (1 success and 3 failure)","","","","0054u000006gpoFAAQ","2025-01-31T16:32:21.000Z"
"0D5Qk00000WAovuKAD","500Qk00000LJtW9IAL","TextPost","0054u000006gpoFAAQ","2025-02-05T17:07:55.000Z","<p>@Nicholas Zimmer​  so interesting.  The scalar error stopped happening on the 3rd of Feb. SO we can see it occur on the 31st/1st/2nd and then it stops on the 3rd and 4th but now we see the constraint error:</p><p> </p><p>System.AggregateException: One or more errors occurred. ---&gt; System.Data.SqlClient.SqlException: Violation of UNIQUE KEY constraint &#39;UQ_SA_AzureADInventory_Principals_ObjectId&#39;. Cannot insert duplicate key in object &#39;dbo.SA_AzureADInventory_Principals&#39;. The duplicate key value is (ad367571-3c8a-4479-901a-3e934be73dd3).</p><p> </p><p>We saw this error and we dropped the tables, it then ran fine 1 time, then we started to see the scaler errors and now we are back to a constraint error.  Super weird.  We dropped the data again and are going to watch how the scan behaves.  We also put in an exclusion for this file in their Anti virus.  Will update on Friday or maybe early next week with some further results</p><p> </p><p> </p>","","","","0054u000006gpoFAAQ","2025-02-05T17:07:55.000Z"
"0D5Qk00000WCoJjKAL","500Qk00000LJtW9IAL","TextPost","0054u000006gpoAAAQ","2025-02-05T23:28:00.000Z","<p>@Catherine LeVoir​ Dev seems to think it was due to a Loss of connection to the Database.</p><p> </p><p>And after reading your comment. thats not great, but also not surprising as it failed due to the other issue. </p><p>however I agree lets see how it plays out.</p>","","","","0054u000006gpoAAAQ","2025-02-05T23:28:00.000Z"
"0D5Qk00000WKVtGKAX","500Qk00000LJtW9IAL","TextPost","0054u000006gpoFAAQ","2025-02-07T15:38:28.000Z","<p>So now its just seems that the Unique constraint error is happening. SO will close this ticket and open a new ticket for the constraint error.  We think due to doing snapshots at 7pm is why they were getting the execute scaler error</p>","","","","0054u000006gpoFAAQ","2025-02-07T15:38:28.000Z"
"0D5Qk00000WKSIzKAP","500Qk00000LJtW9IAL","TextPost","0054u000006gpoFAAQ","2025-02-07T15:38:59.000Z","<p>@Nicholas Zimmer​ did you want to close this case and the escalation?</p>","","","","0054u000006gpoFAAQ","2025-02-07T15:38:59.000Z"
