"Id","CaseNumber","Ticket_Record_Type_Name__c","Subject","Description","DevOps_Steps_to_Reproduce__c","What_We_Know__c","Next_Steps__c","Solution_Comment__c","Issue_Type__c","Ticket_Owner_Name__c","Ticket_Type__c","Platform__c","Collector_Code__c","Feature__c","Product_Version__c","Build_Number__c","Age__c","Status","Account_Name__c","Contact_Name__c","CreatedDate","ClosedDate"
"500Qk00000OnAV8IAN","00444027","Support Ticket","Windows Taks not working anymore","Dear Support 

For the last two weeks we have been receiving the following error message in the scheduler log.
The windows task is running successfully and the ""last report"" date on the web gets updated but no mail is sent.


Exception: Report not imported (System.ArgumentException: An item with the same key has already been added. Key: 4/28/2025 6:00:00 AM
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at <a href='https://System.Linq' target='_blank'>System.Linq</a>.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at <a href='https://System.Linq' target='_blank'>System.Linq</a>.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at PingCastleEnterprise.Services.ScoreHistoryComputer.RecomputeHistory(Nullable`1 OwnerIDToRecompute)
   at PingCastleEnterprise.Services.ReportImporter.AddReportAsync(XmlDocument xmlDocument, String filename, Boolean disableScoreRecomputation, Nullable`1 agentId)
   at <a href='https://PingCastleEnterprise.Controllers.api' target='_blank'>PingCastleEnterprise.Controllers.api</a>.AgentController.SendReport(ReportData report))
   at PingCastle.Tasks.SendViaAPIUploadOneReport(WebClient client, String filename, String xml)
   at PingCastle.Tasks.c__DisplayClass45_0.b__0()
Task Send via API completed


How can this problem be solved?

Best Regards
Andi","","","","User reported an issue with windows tasks.
This was a known bug and was resolved in last release.
Advised user to update.
After the update, the issue was resolved.","Product defect","Shaheryar Ali Tahir","Unexpected Behavior","PingCastle","PC Professional","PingCastle General","3.3","","3.9","Closed - Resolved","Liechtensteinische Landesbank AG","Andi Wirz","2025-05-05T11:19:21.000Z","2025-05-09T08:15:07.000Z"
