"Id","CaseNumber","Ticket_Record_Type_Name__c","Subject","Description","DevOps_Steps_to_Reproduce__c","What_We_Know__c","Next_Steps__c","Solution_Comment__c","Issue_Type__c","Ticket_Owner_Name__c","Ticket_Type__c","Platform__c","Collector_Code__c","Feature__c","Product_Version__c","Build_Number__c","Age__c","Status","Account_Name__c","Contact_Name__c","CreatedDate","ClosedDate"
"500Qk00000PLf6fIAD","00445640","Support Ticket","Exception during scan on the category ""Searching for critical and infrastructure objects","From log file:
[10:25:01 PM]Getting Enumerate page 0
Exception: This request operation sent to <a href='https://net.tcp://galbscdcp99t.bsci.bossci.com' target='_blank'>net.tcp://galbscdcp99t.bsci.bossci.com</a>:9389/ActiveDirectoryWebServices/Windows/Enumeration did not receive a reply within the configured timeout (00:01:00).  The time allotted to this operation may have been a portion of a longer timeout.  This may be because the service is still processing the operation or because the service was unable to send a reply message.  Please consider increasing the operation timeout (by casting the channel/proxy to IContextChannel and setting the OperationTimeout property) and ensure that the service is able to connect to the client.
StackTrace: 
Server stack trace: 
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.Request(Message message, TimeSpan timeout)
   at <a href='https://System.ServiceModel.Channels.ServiceChannel.Call' target='_blank'>System.ServiceModel.Channels.ServiceChannel.Call</a>(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at <a href='https://Search.Pull' target='_blank'>Search.Pull</a>(PullRequest request)
   at <a href='https://PingCastle.ADWS' target='_blank'>PingCastle.ADWS</a>.ADWSConnection.EnumerateInternalWithADWS(String distinguishedName, String filter, String[] properties, String scope, ReceiveItems callback) in c:gitPingCastleADWS<a href='https://ADWSConnection.cs' target='_blank'>ADWSConnection.cs</a>:line 392
   at <a href='https://PingCastle.ADWS' target='_blank'>PingCastle.ADWS</a>.ADWebService.Enumerate(Action preambleWithReentry, String distinguishedName, String filter, String[] properties, WorkOnReturnedObjectByADWS callback, String scope) in c:gitPingCastleADWS<a href='https://ADWebService.cs' target='_blank'>ADWebService.cs</a>:line 289
[10:26:01 PM] Running ldap enumeration
BaseObject=Subtree
Filter=(&(msDS-AllowedToDelegateTo=*)((userAccountControl:1.2.840.113556.1.4.804:=16777216)))
[10:26:01 PM]Calling FindAll
[10:30:02 PM] Warning: received ""Calling GetNextRow can potentially return more results""
[10:32:02 PM]An exception occured
ErrorCode: -2147024662
ExtendedError: 234
ExtendedErrorMessage: Calling GetNextRow can potentially return more results.
numberOfObjectAlreadyExtracted=2
[Red]An exception occured while querying the Active Directory
[Red]Exception: More data is available.
(Calling GetNextRow can potentially return more results.)
[Red]This error occurs when the Active Directory server is under load
[Red]Suggestion: try again and if the error persists, check for AD corruption
[Red]Try our corruption scanner to identify the object or check for AD integrity using <a href='https://ntdsutil.exe' target='_blank'>ntdsutil.exe</a>
Stoping Perform analysis for <a href='https://bsci.bossci.com' target='_blank'>bsci.bossci.com</a> at: 5/19/2025 10:32:02 PM
The task Perform analysis for <a href='https://bsci.bossci.com' target='_blank'>bsci.bossci.com</a> took 00:25:38.7921310
do additional exploration based on trust results ?
done additional exploration","","","","After testing configurations on the server looked like an issue with your AD services or some other firewall/security software.
Resolution: Check with your network/support team internally to resolve the issue with AD.","Backend Server Fix","Shaheryar Ali Tahir","Error","PingCastle","PC Standard","PingCastle General","3.2.0.1","","7.7","Closed - Resolved","Microsoft Corporation","Mike DeFlice","2025-05-19T21:48:20.000Z","2025-05-27T15:21:15.000Z"
