"Id","ParentId","Type","CreatedById","CreatedDate","Body","Title","LinkUrl","RelatedRecordId","InsertedById","LastModifiedDate"
"0D5Qk00000VmG8pKAF","500Qk00000LFbb5IAD","TextPost","0054u000008ARZjAAO","2025-01-30T06:07:24.000Z","Description: Hello Support,

I have two new proxies that I cannot run FS jobs using schedule. The error is below. It works just fine when running the job manually from console (which uses my console login to run the task). I have read that I may need to delete certificates on the proxy, however the service runs as LocalSystem and I cannot deploy psexec. Is there any other troubleshooting that can be done? This was a fresh proxy install a few weeks ago and today was the first time a FS job was run on it. One proxy to one FS host.

FSAA Proxy 11.6.0.35
NEA 11.6.0.112

29/01/2025 22:51:49DEBUGFILESYSTEMACCESSAccessScanTask""Acquiring certificate exchange lock at D:STEALTHbitsStealthAUDITFSAA<a href='https://fsaa_certificate_exchange.lock' target='_blank'>fsaa_certificate_exchange.lock</a>""MDVNAPPDCExtract789265608968
29/01/2025 22:51:49DEBUGFILESYSTEMACCESSAccessScanTask""Using certificate authority: Friendly Name = FSAA Certificate Authority 8/2/2024 9:00:27 PM, Thumbprint = DA07169B26215FF6721E49C9EB8DC7F0A5EFA10B""MDVNAPPDCExtract789265608968
29/01/2025 22:51:49INFOFILESYSTEMACCESSAccessScanTask""Failed to exchange certificates with running proxy service using task credentials, retrying with LocalSystem: Unable to establish secure stream for certificate exchange, requires trusted target domain""MDVNAPPDCExtract789265608968
29/01/2025 22:51:49DEBUGFILESYSTEMACCESSAccessScanTask""Certificate exchange with running proxy service failed: <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.Applet.Client.AppletClientException: Unable to establish secure stream for certificate exchange, requires trusted target domain ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The target principal name is incorrect     --- End of inner exception stack trace ---     at <a href='https://System.Net' target='_blank'>System.Net</a>.Security.NegoState.StartSendAuthResetSignal(LazyAsyncResult lazyResult, Byte[] message, Exception exception)     at <a href='https://System.Net' target='_blank'>System.Net</a>.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)     at <a href='https://System.Net' target='_blank'>System.Net</a>.Security.NegoState.CheckCompletionBeforeNextSend(Byte[] message, LazyAsyncResult lazyResult)     at <a href='https://System.Net' target='_blank'>System.Net</a>.Security.NegoState.ProcessReceivedBlob(Byte[] message, LazyAsyncResult lazyResult)     at <a href='https://System.Net' target='_blank'>System.Net</a>.Security.NegoState.StartReceiveBlob(LazyAsyncResult lazyResult)     at <a href='https://System.Net' target='_blank'>System.Net</a>.Security.NegoState.CheckCompletionBeforeNextReceive(LazyAsyncResult lazyResult)     at <a href='https://System.Net' target='_blank'>System.Net</a>.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)     at <a href='https://System.Net' target='_blank'>System.Net</a>.Security.NegoState.ProcessAuthentication(LazyAsyncResult lazyResult)     at <a href='https://System.Net' target='_blank'>System.Net</a>.Security.NegotiateStream.AuthenticateAsClient(NetworkCredential credential, ChannelBinding binding, String targetName, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel allowedImpersonationLevel)     at <a href='https://System.Net' target='_blank'>System.Net</a>.Security.NegotiateStream.AuthenticateAsClient(NetworkCredential credential, String targetName)     at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.Applet.Client.ClientCertificateManager.UseNegotiateStream[TResult](String host, Int32 port, NetworkCredential credentials, String servicePrincipalName, Func`2 action)     --- End of inner exception stack trace ---     at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.Applet.Client.ClientCertificateManager.UseNegotiateStream[TResult](String host, Int32 port, NetworkCredential credentials, String servicePrincipalName, Func`2 action)     at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.Applet.Client.ClientCertificateManager.IsServerCertificateValid(String host, Int32 port, X509Certificate2 certificateAuthority, NetworkCredential credentials, String servicePrincipalName, Guid exchangeID)     at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.Applet.Client.ClientCertificateManager.ExchangeCertificatesRemote(String host, Int32 port, X509Certificate2 certificateAuthority, NetworkCredential credentials, String servicePrincipalName)     at <a href='https://Stealthbits.StealthAUDIT.Da... [The description has been cut, review the attached email for details]","","","","0054u000008ARZjAAO","2025-01-30T06:07:24.000Z"
"0D5Qk00000VnpLBKAZ","500Qk00000LFbb5IAD","TextPost","0054u000007oss5AAA","2025-01-30T16:09:01.000Z","Invitation updated. Attendees: No attendees listed","","","","0054u000007oss5AAA","2025-01-30T16:09:01.000Z"
"0D5Qk00000VnpLDKAZ","500Qk00000LFbb5IAD","TextPost","0054u000007oss5AAA","2025-01-30T16:09:02.000Z","Invitation updated. Attendees: Joshua Sexton, Justin Cahill","","","","0054u000007oss5AAA","2025-01-30T16:09:02.000Z"
"0D5Qk00000VnpLCKAZ","500Qk00000LFbb5IAD","TextPost","0054u000007oss5AAA","2025-01-30T16:09:02.000Z","Invitation updated. Attendees: Joshua Sexton","","","","0054u000007oss5AAA","2025-01-30T16:09:02.000Z"
"0D5Qk00000VsK5rKAF","500Qk00000LFbb5IAD","TextPost","0054u000007oss5AAA","2025-01-31T15:39:04.000Z","<p><a href=""https://helpcenter.netwrix.com/bundle/EnterpriseAuditor_11.6/page/Content/EnterpriseAuditor/Admin/DataCollector/FSAA/ManualCertificate.htm"" alt=""https://helpcenter.netwrix.com/bundle/EnterpriseAuditor_11.6/page/Content/EnterpriseAuditor/Admin/DataCollector/FSAA/ManualCertificate.htm"" target=""_blank"">FSAA Manual Certificate Configuration</a></p><p>what account is used by the schedule</p><p>is it local admin on the proxy server and FS?</p><p>is the target server in a trusted domain</p><p>is the proxy in the same domain</p><p>Â </p>","","","","0054u000007oss5AAA","2025-01-31T15:39:04.000Z"
"0D5Qk00000VsrFLKAZ","500Qk00000LFbb5IAD","TextPost","0054u000007oss5AAA","2025-01-31T16:43:10.000Z","What We've Learned Updated: all one domain
all using the same service account
lcoal admin on the proxy
-domain admin

FSAA Proxy 11.6.0.37
NEA 11.6.0.112","","","","0054u000007oss5AAA","2025-01-31T16:43:10.000Z"
"0D5Qk00000Vt6FvKAJ","500Qk00000LFbb5IAD","TextPost","0054u000007oss5AAA","2025-01-31T16:59:09.000Z","What We've Learned Updated: all one domain
all using the same service account
local admin on the proxy
-domain admin

works on all the other FS proxies
a dozen of them

This is the only one they are adding since they upgraded from 11.6.0.35

current versions

FSAA Proxy 11.6.0.37
NEA 11.6.0.112

unable to installed PSEXEC so cannot follow KB

all proxies (working and this new one) throw an error about ""invalid principal name""
-other all still work","","","","0054u000007oss5AAA","2025-01-31T16:59:09.000Z"
"0D5Qk00000VtBXXKA3","500Qk00000LFbb5IAD","TextPost","0054u000007oss5AAA","2025-01-31T17:28:49.000Z","<p><a href=""https://helpcenter.netwrix.com/bundle/z-kb-articles-salesforce/page/kA04u0000000HefCAE.html"" alt=""https://helpcenter.netwrix.com/bundle/z-kb-articles-salesforce/page/kA04u0000000HefCAE.html"" target=""_blank"">Cannot Generate SSPI Context Error in SQL Server Monitoring Plan</a></p>","","","","0054u000007oss5AAA","2025-01-31T17:28:49.000Z"
"0D5Qk00000W0SfCKAV","500Qk00000LFbb5IAD","TextPost","0054u000007oss5AAA","2025-02-03T14:00:36.000Z","Invitation updated. Attendees: Joshua Sexton, Tay Caliguiri, Justin Cahill","","","","0054u000007oss5AAA","2025-02-03T14:00:36.000Z"
"0D5Qk00000W0SfBKAV","500Qk00000LFbb5IAD","TextPost","0054u000007oss5AAA","2025-02-03T14:00:36.000Z","Invitation updated. Attendees: Joshua Sexton, Tay Caliguiri","","","","0054u000007oss5AAA","2025-02-03T14:00:36.000Z"
"0D5Qk00000WAfbIKAT","500Qk00000LFbb5IAD","TextPost","0054u000007oss5AAA","2025-02-05T16:26:32.000Z","What We've Learned Updated: all one domain
all using the same service account
local admin on the proxy
-domain admin

works on all the other FS proxies
a dozen of them

This is the only one they are adding since they upgraded from 11.6.0.35

current versions

FSAA Proxy 11.6.0.37
NEA 11.6.0.127

unable to installed PSEXEC so cannot follow KB

all proxies (working and this new one) throw an error about ""invalid principal name""
-other all still work

---------------

this is working now
the issue seems to be NEA ignores the schedule account and tries to apply the cert using the","","","","0054u000007oss5AAA","2025-02-05T16:26:32.000Z"
"0D5Qk00000WAtgoKAD","500Qk00000LFbb5IAD","TextPost","0054u000007oss5AAA","2025-02-05T16:40:56.000Z","What We've Learned Updated: this is working now because the client found a workaround assigning the infostructure account in the Job's properties- so it can laydown the certs
-changing it back afterwards, the job still works because the certs are already there
-this workaround worked on all 3 new proxies having the problem

the issue seems to be NEA ignores the schedule account and tries to apply the cert using the account on the job's properties

There is an error in NEA's job log saying it tried and failed to use the ""task account"" so it tries to use local system which also fails
-makes sense that the NEA server's local system account fails because it doesn't have permissions on the proxy server

---------------
current versions

FSAA Proxy 11.6.0.37
NEA 11.6.0.127
---------------

all one domain
all using the same service account
local admin on the proxy
-domain admin

works on all the other FS proxies
a dozen of them
but these were setup a year ago
the 3 new proxies are all having the same problem

This is the only one they are adding since they upgraded from 11.6.0.35


unable to installed PSEXEC so cannot follow KB

all proxies (working and this new one) throw an error about ""invalid principal name""
-other all still work

---------------","","","","0054u000007oss5AAA","2025-02-05T16:40:56.000Z"
"0D5Qk00000WAZqpKAH","500Qk00000LFbb5IAD","TextPost","0054u000007oss5AAA","2025-02-05T16:43:06.000Z","Next Steps Updated: client:
upload logs from NEA and Proxy servers
-today

NWX Engineer:
1) trim and upload meeting recording that shows issue reproduced and workaround
2) upload document with pertinent timestamps
3) Escalate to T2","","","","0054u000007oss5AAA","2025-02-05T16:43:06.000Z"
"0D5Qk00000WCD0rKAH","500Qk00000LFbb5IAD","TextPost","0054u000007oss5AAA","2025-02-05T20:33:18.000Z","Steps to Reproduce Updated: Configure a FSAA scan that uses a new proxy server to collect from a new File server
-no certs on the proxy yet
-The schedule account has permissions to the proxy server
-The default connection profile in the job uses an account that has permission to the file Server, but not the proxy

run the job for the first time","","","","0054u000007oss5AAA","2025-02-05T20:33:18.000Z"
"0D5Qk00000c6629KAA","500Qk00000LFbb5IAD","TextPost","0054u000006gpoAAAQ","2025-04-18T22:29:56.000Z","Next Steps Updated: 4-18All is working.
Currently determining if we need to update docs or if there is a misunderstanding in how to configure proper credentials for this.","","","","0054u000006gpoAAAQ","2025-04-18T22:29:56.000Z"
"0D5Qk00000d2Ph5KAE","500Qk00000LFbb5IAD","TextPost","0054u000006gpoAAAQ","2025-04-30T21:54:33.000Z","<p>From Luma</p><p>What Justin and You Are Still Trying to Clarify (from the latest emails):</p><ul><li>Is there official documentation or a release noteÂ that states the requirement for a Task(domain) credential for proxy/file system scanning, or was this behavior changed between NEA 11.6.0.112 and 11.6.0.127?</li><li>Why does the system use different credentialsÂ for certificate exchange when running jobs manually (console user) versus scheduled (not the scheduled task account)?</li><li>Is this behavior intentional or a bug,Â and should customers expect to always use a Task(domain) credential for new proxies?</li><li>Should documentation be updatedÂ to clarify these requirements and avoid future confusion?</li></ul><p>Â </p>","","","","0054u000006gpoAAAQ","2025-04-30T21:54:33.000Z"
