"Id","CaseNumber","Ticket_Record_Type_Name__c","Subject","Description","DevOps_Steps_to_Reproduce__c","What_We_Know__c","Next_Steps__c","Solution_Comment__c","Issue_Type__c","Ticket_Owner_Name__c","Ticket_Type__c","Platform__c","Collector_Code__c","Feature__c","Product_Version__c","Build_Number__c","Age__c","Status","Account_Name__c","Contact_Name__c","CreatedDate","ClosedDate"
"500Qk00000E7BpuIAF","00417360","Support Ticket","Filesystem Scans not working","When starting a scan it gives me the following error:

<a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.FSAAException: Unable to start scan: Could not initialize scan session with any proxy host supplied
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.AccessScanTask.InternalProcessRecord()
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task</a>.StartExecute()

I've updated the Netwrix Auditor and the Filesystem Proxy, since we had the a different message regarding Access Violation, which was mentioned in the patch notes.","","","","Customer had a version mismatch between proxy server and NEA. They were updated and then certificates were deleted using KB https://helpcenter.netwrix.com/bundle/z-kb-articles-salesforce/page/kA0Qk0000000WSvKAM.html. Issue is resolved.","Product defect","Saqib Sharif","","Netwrix Enterprise Auditor","StealthAUDIT for Windows File Systems","Access Auditing","11.6","11.6.0.89","14.8","Closed - Resolved","RKW SE","Sean Hanrahan","2024-08-07T08:06:16.000Z","2024-08-22T02:23:00.000Z"
